# Generated by Django 5.1 on 2024-08-31 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='summary',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
