# Generated by Django 5.1 on 2024-08-31 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_record_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='summary',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
